image_folder: ./images
candidate_labels:
  - "a cat"
  - "a dog"
  - "a car"
  - "a bicycle"
  - "a person"
  - "a building"
  - "an outdoor scene"
  - "a microscopic image"
top_k: 3
prompt_template: "Image description: {labels}. Expand into a paragraph about research-relevant observations and potential use-cases:"
